using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SportTrack_Sigdef.AccesoDatos;

#nullable disable

namespace SportTrack_Sigdef.AccesoDatos.Migrations
{
    [DbContext(typeof(SportTrackDbContext))]
    [Migration("20260809120000_AddAudiencePeakSnapshots")]
    public partial class AddAudiencePeakSnapshots : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.""AudiencePeakSnapshots"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""CapturedAtUtc"" timestamp with time zone NOT NULL,
    ""TotalConnections"" integer NOT NULL,
    ""LiveConnections"" integer NOT NULL,
    ""OperatorConnections"" integer NOT NULL,
    ""SoftCapacity"" integer NOT NULL,
    ""SaturationPercent"" double precision NOT NULL,
    ""TopEventoId"" integer NULL,
    ""TopEventoNombre"" character varying(200) NULL,
    ""TopEventoConnections"" integer NOT NULL DEFAULT 0,
    ""IsPeakRecord"" boolean NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS ""IX_AudiencePeakSnapshots_CapturedAtUtc""
    ON public.""AudiencePeakSnapshots"" (""CapturedAtUtc"");

CREATE INDEX IF NOT EXISTS ""IX_AudiencePeakSnapshots_Peak_Total""
    ON public.""AudiencePeakSnapshots"" (""IsPeakRecord"", ""TotalConnections"");
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS public.""AudiencePeakSnapshots"";");
        }
    }
}
