// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportTrack_Sigdef.AccesoDatos;

#nullable disable

namespace SportTrack_Sigdef.AccesoDatos.Migrations
{
    [DbContext(typeof(SportTrackDbContext))]
    [Migration("20260710223802_AddCampanasEnvio")]
    partial class AddCampanasEnvio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.AtletaFederacion", b =>
                {
                    b.Property<int>("ParticipanteId")
                        .HasColumnType("integer");

                    b.Property<bool>("BecadoEnard")
                        .HasColumnType("boolean");

                    b.Property<bool>("BecadoSdn")
                        .HasColumnType("boolean");

                    b.Property<int?>("Categoria")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAptoMedico")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdClub")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederacion")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoBeca")
                        .HasColumnType("numeric");

                    b.Property<bool>("PerteneceSeleccion")
                        .HasColumnType("boolean");

                    b.Property<bool>("PresentoAptoMedico")
                        .HasColumnType("boolean");

                    b.HasKey("ParticipanteId");

                    b.HasIndex("IdClub");

                    b.HasIndex("IdFederacion");

                    b.ToTable("AtletasFederados", "federacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.AtletaFederacionTutor", b =>
                {
                    b.Property<int>("IdAtleta")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("IdTutor")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("Parentesco")
                        .HasColumnType("integer");

                    b.HasKey("IdAtleta", "IdTutor");

                    b.HasIndex("IdTutor");

                    b.ToTable("AtletasTutores", "federacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Bote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo")
                        .IsUnique()
                        .HasDatabaseName("IX_Botes_Tipo");

                    b.ToTable("Botes", "catalogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tipo = "Kayak Individual"
                        },
                        new
                        {
                            Id = 2,
                            Tipo = "Kayak Doble"
                        },
                        new
                        {
                            Id = 3,
                            Tipo = "Kayak Cuadruple"
                        },
                        new
                        {
                            Id = 4,
                            Tipo = "Canoa Individual"
                        },
                        new
                        {
                            Id = 5,
                            Tipo = "Canoa Doble"
                        },
                        new
                        {
                            Id = 6,
                            Tipo = "Canoa Cuadruple"
                        });
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.CampanaEnvio", b =>
                {
                    b.Property<int>("IdCampana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCampana"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("CantidadDestinatarios")
                        .HasColumnType("integer");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EnviadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RemitenteId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoCampana")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdCampana");

                    b.HasIndex("EnviadoEn")
                        .HasDatabaseName("IX_Campanas_EnviadoEn");

                    b.HasIndex("RemitenteId")
                        .HasDatabaseName("IX_Campanas_RemitenteId");

                    b.ToTable("CampanasEnvio", "comunicacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EdadMax")
                        .HasColumnType("integer");

                    b.Property<int?>("EdadMin")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Categorias_Nombre");

                    b.ToTable("Categorias", "catalogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EdadMax = 10,
                            EdadMin = 8,
                            Nombre = "Pre-Infantil"
                        },
                        new
                        {
                            Id = 2,
                            EdadMax = 12,
                            EdadMin = 11,
                            Nombre = "Infantil"
                        },
                        new
                        {
                            Id = 3,
                            EdadMax = 14,
                            EdadMin = 13,
                            Nombre = "Menor"
                        },
                        new
                        {
                            Id = 4,
                            EdadMax = 16,
                            EdadMin = 15,
                            Nombre = "Cadete"
                        },
                        new
                        {
                            Id = 5,
                            EdadMax = 18,
                            EdadMin = 17,
                            Nombre = "Junior"
                        },
                        new
                        {
                            Id = 6,
                            EdadMax = 23,
                            EdadMin = 19,
                            Nombre = "Sub-23"
                        },
                        new
                        {
                            Id = 7,
                            EdadMax = 39,
                            EdadMin = 19,
                            Nombre = "Senior"
                        },
                        new
                        {
                            Id = 8,
                            EdadMax = 49,
                            EdadMin = 40,
                            Nombre = "Master A"
                        },
                        new
                        {
                            Id = 9,
                            EdadMax = 59,
                            EdadMin = 50,
                            Nombre = "Master B"
                        },
                        new
                        {
                            Id = 10,
                            EdadMax = 80,
                            EdadMin = 60,
                            Nombre = "Master C"
                        },
                        new
                        {
                            Id = 11,
                            EdadMax = 99,
                            EdadMin = 0,
                            Nombre = "Control"
                        });
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Club", b =>
                {
                    b.Property<int>("IdClub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClub"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("BloqueadoPorFaltaDePago")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("EstadoMatricula")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAltaPlan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimientoPlan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrecuenciaPago")
                        .HasColumnType("text");

                    b.Property<int?>("IdFederacion")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PagoAfiliacionAlDia")
                        .HasColumnType("boolean");

                    b.Property<int?>("PlanSaaSId")
                        .HasColumnType("integer");

                    b.Property<string>("Siglas")
                        .HasColumnType("text");

                    b.Property<bool>("SolicitudPagoPendiente")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.HasKey("IdClub");

                    b.HasIndex("IdFederacion");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Clubes_Nombre");

                    b.HasIndex("PlanSaaSId");

                    b.ToTable("Clubes", "catalogos");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.DelegadoFederacionClub", b =>
                {
                    b.Property<int?>("IdParticipante")
                        .HasColumnType("integer");

                    b.Property<int?>("ClubIdClub")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederacion")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("IdParticipante");

                    b.HasIndex("ClubIdClub");

                    b.HasIndex("IdFederacion");

                    b.HasIndex("IdRol");

                    b.ToTable("DelegadosClub", "federacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Distancia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistanciaRegata")
                        .HasColumnType("integer");

                    b.Property<int>("GapSugerido")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DistanciaRegata")
                        .IsUnique()
                        .HasDatabaseName("IX_Distancias_DistanciaRegata");

                    b.ToTable("Distancias", "catalogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistanciaRegata = 1,
                            GapSugerido = 5
                        },
                        new
                        {
                            Id = 2,
                            DistanciaRegata = 2,
                            GapSugerido = 5
                        },
                        new
                        {
                            Id = 3,
                            DistanciaRegata = 3,
                            GapSugerido = 5
                        },
                        new
                        {
                            Id = 4,
                            DistanciaRegata = 4,
                            GapSugerido = 5
                        },
                        new
                        {
                            Id = 5,
                            DistanciaRegata = 5,
                            GapSugerido = 7
                        },
                        new
                        {
                            Id = 6,
                            DistanciaRegata = 6,
                            GapSugerido = 10
                        },
                        new
                        {
                            Id = 7,
                            DistanciaRegata = 7,
                            GapSugerido = 10
                        },
                        new
                        {
                            Id = 8,
                            DistanciaRegata = 8,
                            GapSugerido = 10
                        },
                        new
                        {
                            Id = 9,
                            DistanciaRegata = 9,
                            GapSugerido = 15
                        },
                        new
                        {
                            Id = 10,
                            DistanciaRegata = 10,
                            GapSugerido = 15
                        },
                        new
                        {
                            Id = 11,
                            DistanciaRegata = 11,
                            GapSugerido = 20
                        },
                        new
                        {
                            Id = 12,
                            DistanciaRegata = 12,
                            GapSugerido = 20
                        },
                        new
                        {
                            Id = 13,
                            DistanciaRegata = 13,
                            GapSugerido = 25
                        },
                        new
                        {
                            Id = 14,
                            DistanciaRegata = 14,
                            GapSugerido = 25
                        },
                        new
                        {
                            Id = 15,
                            DistanciaRegata = 15,
                            GapSugerido = 30
                        },
                        new
                        {
                            Id = 16,
                            DistanciaRegata = 16,
                            GapSugerido = 40
                        });
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.DocumentacionFederacionPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("TipoDocumento")
                        .HasColumnType("integer");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("DocumentacionPersonas", "federacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.EntrenadorFederacion", b =>
                {
                    b.Property<int>("ParticipanteId")
                        .HasColumnType("integer");

                    b.Property<bool?>("BecadoEnard")
                        .HasColumnType("boolean");

                    b.Property<bool?>("BecadoSdn")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoriaSeleccion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("IdClub")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederacion")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MontoBeca")
                        .HasColumnType("numeric");

                    b.Property<bool?>("PerteneceSeleccion")
                        .HasMaxLength(50)
                        .HasColumnType("boolean");

                    b.Property<bool?>("PresentoAptoMedico")
                        .HasColumnType("boolean");

                    b.HasKey("ParticipanteId");

                    b.HasIndex("IdClub");

                    b.HasIndex("IdFederacion");

                    b.ToTable("Entrenadores", "federacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventoPruebaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventoPruebaId");

                    b.ToTable("Etapas", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvento"));

                    b.Property<string>("BotesHabilitados")
                        .HasColumnType("text");

                    b.Property<int>("CarrilesDisponibles")
                        .HasColumnType("integer");

                    b.Property<string>("CategoriasHabilitadas")
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("DistanciasHabilitadas")
                        .HasColumnType("text");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Programada");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFinInscripciones")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicioInscripciones")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GapEntrePruebas")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFinReceso")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicioEvento")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicioReceso")
                        .HasColumnType("interval");

                    b.Property<int?>("IdClub")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederacion")
                        .HasColumnType("integer");

                    b.Property<bool>("InscripcionesHabilitadas")
                        .HasColumnType("boolean");

                    b.Property<bool>("LimitacionBotesAB")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("PerfilTiempo")
                        .HasColumnType("integer");

                    b.Property<bool>("PermitirCombinadas")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirCompletarK4")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirMasterBajarASenior")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitirSub23EnSenior")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("numeric");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<bool>("RequiereCertificadoMedico")
                        .HasColumnType("boolean");

                    b.Property<bool>("RestringirSoloCategoriaPropia")
                        .HasColumnType("boolean");

                    b.Property<bool>("SinReceso")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneCronometraje")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("UsarGapVariable")
                        .HasColumnType("boolean");

                    b.HasKey("IdEvento");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Eventos_Estado");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_Eventos_Fecha");

                    b.HasIndex("IdClub");

                    b.HasIndex("IdFederacion");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Eventos_Nombre");

                    b.ToTable("Eventos", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.EventoPrueba", b =>
                {
                    b.Property<int>("IdEventoPrueba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEventoPrueba"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Programada");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEvento")
                        .HasColumnType("integer");

                    b.Property<int>("IdPrueba")
                        .HasColumnType("integer");

                    b.Property<int>("MaxParticipantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Pista")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlanProgresionAsignado")
                        .HasColumnType("text");

                    b.Property<decimal?>("PrecioCategoria")
                        .HasColumnType("numeric");

                    b.HasKey("IdEventoPrueba");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_EventoPruebas_Estado");

                    b.HasIndex("FechaHora")
                        .HasDatabaseName("IX_EventoPruebas_FechaHora");

                    b.HasIndex("IdPrueba");

                    b.HasIndex("IdEvento", "IdPrueba", "FechaHora")
                        .IsUnique()
                        .HasDatabaseName("IX_EventoPruebas_EventoPrueba_Fecha");

                    b.ToTable("EventoPruebas", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Fase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EtapaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaHoraFinReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraInicioReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreFase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NumeroFase")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.ToTable("Fases", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Federacion", b =>
                {
                    b.Property<int>("IdFederacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFederacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("BancoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("BloqueadaPorFaltaDePago")
                        .HasColumnType("boolean");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailCobro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FechaAltaPlan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimientoPlan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrecuenciaPago")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PlanSaaSId")
                        .HasColumnType("integer");

                    b.Property<string>("Sigla")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TitularCuenta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdFederacion");

                    b.HasIndex("PlanSaaSId");

                    b.ToTable("Federaciones", "federacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Hilo", b =>
                {
                    b.Property<int>("IdHilo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHilo"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdCampana")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UltimoMensajeEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdHilo");

                    b.HasIndex("IdCampana")
                        .HasDatabaseName("IX_Hilos_IdCampana");

                    b.HasIndex("UltimoMensajeEn")
                        .HasDatabaseName("IX_Hilos_UltimoMensajeEn");

                    b.ToTable("Hilos", "comunicacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInscripcion"));

                    b.Property<int?>("AtletaFederacionParticipanteId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsCabezaDeSerie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Inscrito");

                    b.Property<DateTime>("FechaInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdEventoPrueba")
                        .HasColumnType("integer");

                    b.Property<int?>("IdParticipante")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroCompetidor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Pagado")
                        .HasColumnType("boolean");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("AtletaFederacionParticipanteId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Inscripciones_Estado");

                    b.HasIndex("FechaInscripcion")
                        .HasDatabaseName("IX_Inscripciones_FechaInscripcion");

                    b.HasIndex("IdEventoPrueba");

                    b.HasIndex("IdParticipante")
                        .HasDatabaseName("IX_Inscripciones_ParticipanteId");

                    b.HasIndex("NumeroCompetidor")
                        .HasDatabaseName("IX_Inscripciones_NumeroCompetidor");

                    b.ToTable("Inscripciones", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.InscripcionTripulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InscripcionId")
                        .HasColumnType("integer");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("integer");

                    b.Property<int?>("PosicionEnBote")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("InscripcionId", "ParticipanteId")
                        .IsUnique()
                        .HasDatabaseName("IX_InscripcionTripulantes_Unica");

                    b.ToTable("InscripcionTripulantes", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Mensaje", b =>
                {
                    b.Property<int>("IdMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMensaje"));

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("integer");

                    b.Property<bool>("EliminadoPorDestinatario")
                        .HasColumnType("boolean");

                    b.Property<bool>("EliminadoPorRemitente")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EnviadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HiloId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LeidoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RemitenteId")
                        .HasColumnType("integer");

                    b.HasKey("IdMensaje");

                    b.HasIndex("DestinatarioId")
                        .HasDatabaseName("IX_Mensajes_DestinatarioId");

                    b.HasIndex("HiloId")
                        .HasDatabaseName("IX_Mensajes_HiloId");

                    b.HasIndex("RemitenteId");

                    b.HasIndex("DestinatarioId", "LeidoEn")
                        .HasDatabaseName("IX_Mensajes_Destinatario_Leido");

                    b.ToTable("Mensajes", "comunicacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClubId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("InscripcionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ParticipanteId")
                        .HasColumnType("integer");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegistradoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("ParticipanteId");

                    b.ToTable("Pagos", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.PagoFederacionTransaccion", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdClub")
                        .HasColumnType("integer");

                    b.Property<string>("IdMercadoPago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdParticipante")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.HasKey("IdPago");

                    b.HasIndex("IdClub");

                    b.HasIndex("IdParticipante");

                    b.ToTable("PagosTransacciones", "federacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Participante", b =>
                {
                    b.Property<int>("ParticipanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParticipanteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<string>("Documento")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int?>("IdClub")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PagoAfiliacionAlDia")
                        .HasColumnType("boolean");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SexoId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ParticipanteId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("IX_Participantes_Documento")
                        .HasFilter("\"Documento\" IS NOT NULL AND \"Documento\" <> ''");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Participantes_Email")
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("IdClub")
                        .HasDatabaseName("IX_Participantes_ClubId");

                    b.HasIndex("Pais")
                        .HasDatabaseName("IX_Participantes_Pais");

                    b.HasIndex("SexoId")
                        .HasDatabaseName("IX_Participantes_SexoId");

                    b.HasIndex("Nombre", "Apellido")
                        .HasDatabaseName("IX_Participantes_NombreApellido");

                    b.ToTable("Participantes", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Penalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("JuezAsignado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ResultadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<TimeSpan?>("TiempoPenalizacion")
                        .HasColumnType("interval");

                    b.Property<string>("TipoPenalizacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("JuezAsignado")
                        .HasDatabaseName("IX_Penalizaciones_JuezAsignado");

                    b.HasIndex("ResultadoId")
                        .HasDatabaseName("IX_Penalizaciones_ResultadoId");

                    b.HasIndex("Severidad")
                        .HasDatabaseName("IX_Penalizaciones_Severidad");

                    b.HasIndex("TipoPenalizacion")
                        .HasDatabaseName("IX_Penalizaciones_TipoPenalizacion");

                    b.HasIndex("ResultadoId", "TipoPenalizacion")
                        .HasDatabaseName("IX_Penalizaciones_ResultadoTipo");

                    b.ToTable("Penalizaciones", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.PlanSaaS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ExportacionExcel")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAtletas")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTorneosActivos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("ResultadosTiempoReal")
                        .HasColumnType("boolean");

                    b.Property<bool>("SoportePrioritario")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_PlanesSaaS_Nombre");

                    b.ToTable("PlanesSaaS", "catalogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExportacionExcel = false,
                            MaxAtletas = 500,
                            MaxTorneosActivos = 5,
                            Nombre = "SIGDEF (S)",
                            Precio = 50m,
                            ResultadosTiempoReal = false,
                            SoportePrioritario = false
                        },
                        new
                        {
                            Id = 2,
                            ExportacionExcel = false,
                            MaxAtletas = 2000,
                            MaxTorneosActivos = 20,
                            Nombre = "SIGDEF (M)",
                            Precio = 120m,
                            ResultadosTiempoReal = false,
                            SoportePrioritario = false
                        },
                        new
                        {
                            Id = 3,
                            ExportacionExcel = true,
                            MaxAtletas = -1,
                            MaxTorneosActivos = -1,
                            Nombre = "SIGDEF (L)",
                            Precio = 250m,
                            ResultadosTiempoReal = true,
                            SoportePrioritario = true
                        },
                        new
                        {
                            Id = 4,
                            ExportacionExcel = false,
                            MaxAtletas = 500,
                            MaxTorneosActivos = 5,
                            Nombre = "SportTrack (S)",
                            Precio = 40m,
                            ResultadosTiempoReal = false,
                            SoportePrioritario = false
                        },
                        new
                        {
                            Id = 5,
                            ExportacionExcel = false,
                            MaxAtletas = 2000,
                            MaxTorneosActivos = 20,
                            Nombre = "SportTrack (M)",
                            Precio = 90m,
                            ResultadosTiempoReal = false,
                            SoportePrioritario = false
                        },
                        new
                        {
                            Id = 6,
                            ExportacionExcel = true,
                            MaxAtletas = -1,
                            MaxTorneosActivos = -1,
                            Nombre = "SportTrack (L)",
                            Precio = 190m,
                            ResultadosTiempoReal = true,
                            SoportePrioritario = true
                        },
                        new
                        {
                            Id = 7,
                            ExportacionExcel = true,
                            MaxAtletas = 500,
                            MaxTorneosActivos = 5,
                            Nombre = "Pack Dúo (S)",
                            Precio = 75m,
                            ResultadosTiempoReal = true,
                            SoportePrioritario = true
                        },
                        new
                        {
                            Id = 8,
                            ExportacionExcel = true,
                            MaxAtletas = 2000,
                            MaxTorneosActivos = 20,
                            Nombre = "Pack Dúo (M)",
                            Precio = 170m,
                            ResultadosTiempoReal = true,
                            SoportePrioritario = true
                        },
                        new
                        {
                            Id = 9,
                            ExportacionExcel = true,
                            MaxAtletas = -1,
                            MaxTorneosActivos = -1,
                            Nombre = "Pack Dúo (L)",
                            Precio = 350m,
                            ResultadosTiempoReal = true,
                            SoportePrioritario = true
                        });
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Prueba", b =>
                {
                    b.Property<int>("IdPrueba")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrueba"));

                    b.Property<int>("CategoriaEdad")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DistanciaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SexoCompetencia")
                        .HasColumnType("integer");

                    b.Property<int>("TipoBote")
                        .HasColumnType("integer");

                    b.HasKey("IdPrueba");

                    b.HasIndex("CategoriaEdad");

                    b.HasIndex("DistanciaId");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Pruebas_Nombre");

                    b.HasIndex("SexoCompetencia");

                    b.HasIndex("TipoBote", "CategoriaEdad", "DistanciaId", "SexoCompetencia")
                        .IsUnique()
                        .HasDatabaseName("IX_Pruebas_Unica");

                    b.ToTable("Pruebas", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.ReglaProgresion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadATomar")
                        .HasColumnType("integer");

                    b.Property<int>("EtapaDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("EtapaOrigenId")
                        .HasColumnType("integer");

                    b.Property<int>("EventoPruebaId")
                        .HasColumnType("integer");

                    b.Property<bool>("PorTiempo")
                        .HasColumnType("boolean");

                    b.Property<int>("PosicionDesde")
                        .HasColumnType("integer");

                    b.Property<int>("PosicionHasta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EtapaDestinoId");

                    b.HasIndex("EtapaOrigenId");

                    b.HasIndex("EventoPruebaId");

                    b.ToTable("ReglasProgresion", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Resultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Carril")
                        .HasColumnType("integer");

                    b.Property<bool>("EsCabezaDeSerie")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<int>("FaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("FaseOrigenId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int?>("Posicion")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Puntos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ReglaClasificacionAplicada")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("TiempoOficial")
                        .HasColumnType("interval");

                    b.Property<string>("UsuarioActualizacion")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioRegistro")
                        .HasColumnType("text");

                    b.Property<decimal?>("VelocidadMedia")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("FaseId", "Carril")
                        .HasDatabaseName("IX_Resultados_Carril");

                    b.ToTable("Resultados", "regatas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.RolFederacion", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles", "federacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Sexos_Nombre");

                    b.ToTable("Sexos", "catalogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Masculino"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Femenino"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Mixto"
                        });
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.TutorFederacion", b =>
                {
                    b.Property<int>("ParticipanteId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTutor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ParticipanteId");

                    b.ToTable("Tutores", "federacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdClub")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederacion")
                        .HasColumnType("integer");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<int?>("ParticipanteId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RolFederacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdClub");

                    b.HasIndex("IdFederacion");

                    b.HasIndex("ParticipanteId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios", "seguridad");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Email = "admin@sporttrack.com",
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntentosFallidos = 0,
                            PasswordHash = "$2a$12$6ET.51wRwWnd/mscg3c8l.DcgbMBbQmVSqJ/pHpUcpNAPe4mzxoOS",
                            RolFederacion = "SuperAdmin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.AtletaFederacion", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Club", "Club")
                        .WithMany("AtletasFederados")
                        .HasForeignKey("IdClub");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Federacion", "Federacion")
                        .WithMany("AtletasFederados")
                        .HasForeignKey("IdFederacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Participante", "Participante")
                        .WithOne("AtletaFederacion")
                        .HasForeignKey("SportTrack_Sigdef.Entidades.Entidades.AtletaFederacion", "ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Federacion");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.AtletaFederacionTutor", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.AtletaFederacion", "AtletaFederacion")
                        .WithMany("Tutores")
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.TutorFederacion", "TutorFederacion")
                        .WithMany("AtletasTutores")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtletaFederacion");

                    b.Navigation("TutorFederacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.CampanaEnvio", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Usuario", "Remitente")
                        .WithMany()
                        .HasForeignKey("RemitenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Campanas_Remitente");

                    b.Navigation("Remitente");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Club", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Federacion", "Federacion")
                        .WithMany("Clubes")
                        .HasForeignKey("IdFederacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.PlanSaaS", "PlanSaaS")
                        .WithMany("Clubes")
                        .HasForeignKey("PlanSaaSId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Federacion");

                    b.Navigation("PlanSaaS");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.DelegadoFederacionClub", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Club", "Club")
                        .WithMany("Representantes")
                        .HasForeignKey("ClubIdClub");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Federacion", "Federacion")
                        .WithMany("DelegadosClub")
                        .HasForeignKey("IdFederacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Participante", "Participante")
                        .WithOne("DelegadoFederacionClub")
                        .HasForeignKey("SportTrack_Sigdef.Entidades.Entidades.DelegadoFederacionClub", "IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.RolFederacion", "RolFederacion")
                        .WithMany("DelegadosClub")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Federacion");

                    b.Navigation("Participante");

                    b.Navigation("RolFederacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.DocumentacionFederacionPersona", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Participante", "Participante")
                        .WithMany("Documentacion")
                        .HasForeignKey("PersonaId");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.EntrenadorFederacion", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Club", "Club")
                        .WithMany("Entrenadores")
                        .HasForeignKey("IdClub");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Federacion", "Federacion")
                        .WithMany("Entrenadores")
                        .HasForeignKey("IdFederacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Participante", "Participante")
                        .WithOne("EntrenadorFederacion")
                        .HasForeignKey("SportTrack_Sigdef.Entidades.Entidades.EntrenadorFederacion", "ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Federacion");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Etapa", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.EventoPrueba", "EventoPrueba")
                        .WithMany("Etapas")
                        .HasForeignKey("EventoPruebaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Etapas_EventoPruebas");

                    b.Navigation("EventoPrueba");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Evento", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Federacion", "Federacion")
                        .WithMany("Eventos")
                        .HasForeignKey("IdFederacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Club");

                    b.Navigation("Federacion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.EventoPrueba", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Evento", "Evento")
                        .WithMany("EventoPruebas")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EventoPruebas_Eventos");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Prueba", "Prueba")
                        .WithMany("EventoPruebas")
                        .HasForeignKey("IdPrueba")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventoPruebas_Pruebas");

                    b.Navigation("Evento");

                    b.Navigation("Prueba");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Fase", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Etapa", "Etapa")
                        .WithMany("Fases")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Fases_Etapas");

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Federacion", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.PlanSaaS", "PlanSaaS")
                        .WithMany("Federaciones")
                        .HasForeignKey("PlanSaaSId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlanSaaS");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Hilo", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.CampanaEnvio", "Campana")
                        .WithMany("Hilos")
                        .HasForeignKey("IdCampana")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Hilos_Campanas");

                    b.Navigation("Campana");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Inscripcion", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.AtletaFederacion", null)
                        .WithMany("Inscripciones")
                        .HasForeignKey("AtletaFederacionParticipanteId");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.EventoPrueba", "EventoPrueba")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdEventoPrueba")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Inscripciones_EventoPruebas");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Participante", "Participante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdParticipante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Inscripciones_Participantes");

                    b.Navigation("EventoPrueba");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.InscripcionTripulante", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Inscripcion", "Inscripcion")
                        .WithMany("Tripulantes")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InscripcionTripulantes_Inscripciones");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InscripcionTripulantes_Participantes");

                    b.Navigation("Inscripcion");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Mensaje", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Usuario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Mensajes_Destinatario");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Hilo", "Hilo")
                        .WithMany("Mensajes")
                        .HasForeignKey("HiloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Mensajes_Hilos");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Usuario", "Remitente")
                        .WithMany()
                        .HasForeignKey("RemitenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Mensajes_Remitente");

                    b.Navigation("Destinatario");

                    b.Navigation("Hilo");

                    b.Navigation("Remitente");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Pago", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Pagos_Clubes");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Pagos_Inscripciones");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Pagos_Participantes");

                    b.Navigation("Club");

                    b.Navigation("Inscripcion");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.PagoFederacionTransaccion", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Club", "Club")
                        .WithMany("Pagos")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Participante", "Participante")
                        .WithMany("Pagos")
                        .HasForeignKey("IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Participante", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Categoria", "Categoria")
                        .WithMany("Participantes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Participantes_Categorias");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Club", "Club")
                        .WithMany("Participantes")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Participantes_Clubes");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Sexo", "Sexo")
                        .WithMany("Participantes")
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Participantes_Sexos");

                    b.Navigation("Categoria");

                    b.Navigation("Club");

                    b.Navigation("Sexo");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Penalizacion", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Resultado", "Resultado")
                        .WithMany("Penalizaciones")
                        .HasForeignKey("ResultadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Penalizaciones_Resultados");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Prueba", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Categoria", "Categoria")
                        .WithMany("Pruebas")
                        .HasForeignKey("CategoriaEdad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pruebas_Categorias");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Distancia", "Distancia")
                        .WithMany("Pruebas")
                        .HasForeignKey("DistanciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pruebas_Distancias");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Sexo", "Sexo")
                        .WithMany("Pruebas")
                        .HasForeignKey("SexoCompetencia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pruebas_Sexos");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Bote", "Bote")
                        .WithMany("Pruebas")
                        .HasForeignKey("TipoBote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pruebas_Botes");

                    b.Navigation("Bote");

                    b.Navigation("Categoria");

                    b.Navigation("Distancia");

                    b.Navigation("Sexo");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.ReglaProgresion", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Etapa", "EtapaDestino")
                        .WithMany("ReglasComoDestino")
                        .HasForeignKey("EtapaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReglasProgresion_Etapas_Destino");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Etapa", "EtapaOrigen")
                        .WithMany("ReglasComoOrigen")
                        .HasForeignKey("EtapaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReglasProgresion_Etapas_Origen");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.EventoPrueba", "EventoPrueba")
                        .WithMany("ReglasProgresion")
                        .HasForeignKey("EventoPruebaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReglasProgresion_EventoPruebas");

                    b.Navigation("EtapaDestino");

                    b.Navigation("EtapaOrigen");

                    b.Navigation("EventoPrueba");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Resultado", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Fase", "Fase")
                        .WithMany("Resultados")
                        .HasForeignKey("FaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Resultados_Fases");

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Inscripcion", "Inscripcion")
                        .WithMany("Resultados")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Resultados_Inscripciones");

                    b.Navigation("Fase");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.TutorFederacion", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Participante", "Participante")
                        .WithOne("TutorFederacion")
                        .HasForeignKey("SportTrack_Sigdef.Entidades.Entidades.TutorFederacion", "ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Usuario", b =>
                {
                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Club", "Club")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdClub")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Federacion", "Federacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdFederacion")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportTrack_Sigdef.Entidades.Entidades.Participante", "Participante")
                        .WithOne("Usuario")
                        .HasForeignKey("SportTrack_Sigdef.Entidades.Entidades.Usuario", "ParticipanteId");

                    b.Navigation("Club");

                    b.Navigation("Federacion");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.AtletaFederacion", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Bote", b =>
                {
                    b.Navigation("Pruebas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.CampanaEnvio", b =>
                {
                    b.Navigation("Hilos");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Categoria", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Pruebas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Club", b =>
                {
                    b.Navigation("AtletasFederados");

                    b.Navigation("Entrenadores");

                    b.Navigation("Pagos");

                    b.Navigation("Participantes");

                    b.Navigation("Representantes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Distancia", b =>
                {
                    b.Navigation("Pruebas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Etapa", b =>
                {
                    b.Navigation("Fases");

                    b.Navigation("ReglasComoDestino");

                    b.Navigation("ReglasComoOrigen");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Evento", b =>
                {
                    b.Navigation("EventoPruebas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.EventoPrueba", b =>
                {
                    b.Navigation("Etapas");

                    b.Navigation("Inscripciones");

                    b.Navigation("ReglasProgresion");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Fase", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Federacion", b =>
                {
                    b.Navigation("AtletasFederados");

                    b.Navigation("Clubes");

                    b.Navigation("DelegadosClub");

                    b.Navigation("Entrenadores");

                    b.Navigation("Eventos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Hilo", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Inscripcion", b =>
                {
                    b.Navigation("Resultados");

                    b.Navigation("Tripulantes");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Participante", b =>
                {
                    b.Navigation("AtletaFederacion");

                    b.Navigation("DelegadoFederacionClub");

                    b.Navigation("Documentacion");

                    b.Navigation("EntrenadorFederacion");

                    b.Navigation("Inscripciones");

                    b.Navigation("Pagos");

                    b.Navigation("TutorFederacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.PlanSaaS", b =>
                {
                    b.Navigation("Clubes");

                    b.Navigation("Federaciones");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Prueba", b =>
                {
                    b.Navigation("EventoPruebas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Resultado", b =>
                {
                    b.Navigation("Penalizaciones");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.RolFederacion", b =>
                {
                    b.Navigation("DelegadosClub");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.Sexo", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Pruebas");
                });

            modelBuilder.Entity("SportTrack_Sigdef.Entidades.Entidades.TutorFederacion", b =>
                {
                    b.Navigation("AtletasTutores");
                });
#pragma warning restore 612, 618
        }
    }
}
