using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SportTrack_Sigdef.AccesoDatos;

#nullable disable

namespace SportTrack_Sigdef.AccesoDatos.Migrations
{
    [DbContext(typeof(SportTrackDbContext))]
    [Migration("20260823150000_AddTimingSubmissionOutbox")]
    public partial class AddTimingSubmissionOutbox : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS public.""TimingSubmissionOutbox"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""FaseId"" integer NOT NULL,
    ""EventoId"" integer NULL,
    ""Username"" character varying(100) NOT NULL,
    ""PayloadJson"" text NOT NULL,
    ""SoloMode"" boolean NOT NULL DEFAULT FALSE,
    ""CreatedAtUtc"" timestamp with time zone NOT NULL,
    ""ExpiresAtUtc"" timestamp with time zone NOT NULL,
    ""AttemptCount"" integer NOT NULL DEFAULT 0,
    ""LastAttemptAtUtc"" timestamp with time zone NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ""IX_TimingSubmissionOutbox_Fase_Username""
    ON public.""TimingSubmissionOutbox"" (""FaseId"", ""Username"");

CREATE INDEX IF NOT EXISTS ""IX_TimingSubmissionOutbox_Username_Expires""
    ON public.""TimingSubmissionOutbox"" (""Username"", ""ExpiresAtUtc"");
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS public.""TimingSubmissionOutbox"";");
        }
    }
}
